<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>BIMLawyer</AssemblyName>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>/Applications/Autodesk/Revit 2024/RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>/Applications/Autodesk/Revit 2024/RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
  </ItemGroup>

  <Target Name="AfterBuild">
    <Copy SourceFiles="BIMLawyer.addin" DestinationFolder="$(AppData)\Autodesk\Revit\Addins\2024" />
    <Copy SourceFiles="$(OutputPath)BIMLawyer.dll" DestinationFolder="$(AppData)\Autodesk\Revit\Addins\2024" />
  </Target>
</Project>
